/*----- BASE DE DATOS  -----*/
DROP DATABASE dbConferenceVG;
create database dbConferenceVG;
USE dbConferenceVG;

/*----- CREACION DE TABLAS -----*/
/*(3)Crear la tabla PARTICIPANTE.*/
CREATE TABLE PARTICIPANTE(
IDPAR INT AUTO_INCREMENT,
FECREGPAR DATE ,
NOMPAR VARCHAR (60),
APEPAR VARCHAR (80),
DNIPAR CHAR(8),
TIPPAR CHAR(1),
CELPAR CHAR(9), 
EMAPAR VARCHAR(90), 
DIRPAR VARCHAR(90), 
ESTPAR CHAR(1),
FOREIGN KEY IDPART_PK  (IDPAR)
);

/* SELECT CURDATE();*/

/*(4)Crear tabla PONENTE.*/
CREATE TABLE PONENTE(
CODPON CHAR(6),
NOMPON VARCHAR(60),
APEPON VARCHAR(80),
CELPON CHAR(9),
DNIPON CHAR(8),
EMAPON VARCHAR(90),
DIRPON VARCHAR(90)
);

/*(5)Crear tabla CONFERENCIA.*/
CREATE TABLE CONFERENCIA(
CODCONF CHAR(5),
TEMCONF VARCHAR(90),
FECCONF DATE,
PONCONF CHAR(5)
);

/*(6)Crear tabla REGISTRO.*/
CREATE TABLE REGISTRO(
CODREG CHAR(5),
CODPAR INT,
FECREG DATE,
CERTREG CHAR(1)
);

/*(7)Crear tabla REGISTRODETALLE.*/
CREATE TABLE REGISTRODETALLE(
IDREGDET INT AUTO_INCREMENT,
CODREG CHAR(5),
CODCONF CHAR(5),
CANTPART INT,
FOREIGN KEY IDREGDET_PK  
);

/*-----(8) RELACIONAR TABLAS -----*/

/*PARTICIPANTES-REGISTRO*/
ALTER TABLE PARTICIPANTES
	FOREIGN KEY REGISTRO(CODREG_PK) PARTICIPANTES(CODREG_PK);
	
/*REGISTRO-REGISTRODETALLE*/
ALTER TABLE REGISTRO
	FOREIGN KEY REGISTRO(CODREG_PK)
    
/*CONFERENCIA-REGISTRODETALLE*/

/*PONENTE-CONFERENCIA*/

/*INSERTAR DATOS*/

/*(9)INSERTAR DATOS A PARTICIPANTE*/
INSERT INTO PARTICIPANTE 
	(NOMPAR,APEPAR,DNIPAR,TIPPAR),
	("Juan","Campos Perez",40255133,1,986512478,"juan.campos@vallegrande.edu.pe","Av. Miraflores","A")
	;
/*(10)INSERTAR DATOS A PONENTE*/
INSERT INTO PONENTE
	(CODPON,NOMPON,APEPON,CELPON,DNIPON,EMAPON,DIRPON),
	("P0001","Alberto","Corrales Lonza",,15263798,"alberto.corrales@yahoo.com","Calle Los Portales");
/*(11)INSERTAR DATOS A CONFERENCIA*/

/*(12)INSERTAR DATOS A REGISTRO*/

/*(13)INSERTAR DATOS A REGISTRODETALLE*/

/*(14)CREAR VISTA DATOS A ESTUDIANTES*/

/*(14)INSERTAR DATOS A ESTUDIANTES*/


/*----- CREACION DE VISTAS -----*/

/*(14) CREACION DE VISTA PARTICIPANTES*/
CREATE VIEW ESTUDIANTES (APEPAR,NOMPAR,CELPAR,EMAPAR) AS (APELLIDO,NOMBRE,CELULAR,EMAIL);

/*(15) CREACION DE VISTA PONENTES, TEMA Y FECHA*/
CREATE VIEW PONENTES (APEPON,NOMPON,TEMCONF,FECCONF) AS (APELLIDO,NOMBRE,TEMA,FECHA);


/*(16)*/


/* (17)---- INNER JOIN ----- */

SELECT 
	


